# Generated by Django 5.1 on 2024-11-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('blog', 'Blog'), ('api', 'API')], default='blog', max_length=10),
        ),
    ]
