# Generated by Django 5.1 on 2024-12-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_badge_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='weekly_login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
