# Generated by Django 5.1 on 2024-10-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
